---
version: "3.7"

services:
  openresty:
    build: .

    network_mode: bridge

    environment:
      OPENRESTY_APP_LABEL: com.dokku.app-name
      OPENRESTY_PROCESS_LABEL: com.dokku.process-type
      OPENRESTY_LABEL_PREFIX: openresty.
      OPENRESTY_WEB_PROCESS: web
      OPENRESTY_DEFAULT_NETWORK: bridge

    ports:
      - "8080:80"
      - "8443:443"

    restart: unless-stopped

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
